version: '3'

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure