version: '3' # Docker compose version

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress # Container virtual path
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
  
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql  
    restart: unless-stopped
    expose:
      - "3306"
  
volumes:
  wordpress:
    driver: local # Data is stored locally (on host machine)
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vnaslund/data/wordpress' # Data from container is mapped to
  
  mariadb:
    driver: local 
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vnaslund/data/mariadb'

networks:
  inception:
    driver: bridge # Private internal network, allows containers to communicate
# The services can only be accessed from outside the host on exposed ports