services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: inception-nginx:latest
    container_name: nginx
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception-network

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: inception-wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception-network
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    image: inception-mariadb:latest
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception-network
    env_file:
      - .env

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress-data:
  mariadb-data: